<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ros2_service_server_cpp</name>
  <version>0.0.1</version>
  <description>Example ROS 2 C++ service servers.</description>
  <maintainer email="developer@example.com">ROS 2 Developer</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>add_two_float_interfaces</depend>
  <depend>example_interfaces</depend>
  <depend>rclcpp</depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
